package com.pettoyou.server.pet.entity.enums;

public enum Species {

    /***
     * 고양이 종류
     */
    ABYSSINIAN("아비시니안"),
    AMERICAN_BOBTAIL("아메리칸 밥테일"),
    AMERICAN_CURL("아메리칸 컬"),
    AMERICAN_RINGTAIL("아메리칸 링테일"),
    AMERICAN_SHORTHAIR("아메리칸 쇼트헤어"),
    AMERICAN_WIREHAIR("아메리칸 와이어헤어"),
    ANATOLI("아나톨리"),
    CYPRUS("키프로스"),
    CYPRUS_APHRODITE("키프로스 아프로디테"),
    ARABIAN_MAU("아라비안 마우"),
    ASIAN("아시안"),
    TIFFANY("티파니"),
    AUSTRALIAN_MIST("오스트레일리안 미스트"),
    AUSTRALIAN_TIFFANY("오스트레일리안 티파니"),
    BAHRAIN_DILMUN("바레인 딜문"),
    BALINESE("발리니즈"),
    BAMBINO("밤비노"),
    BENGAL("벵갈"),
    BIRMAN("버먼"),
    BOMBAY("봄베이"),
    BRAMBLE("브램블"),
    BRAZILIAN_SHORTHAIR("브라질리안 쇼트헤어"),
    BRITISH_LONGHAIR("브리티시 롱헤어"),
    BRITISH_SHORTHAIR("브리티시 쇼트헤어"),
    BURMESE("버미즈"),
    BURMILLA("버밀라"),
    CALIFORNIA_SPANGLED("캘리포니아 스팽글드"),
    CEYLON("세일론"),
    CHANTILLY_TIFFANY("샹틸리 티파니"),
    CHARTREUX("샤르트뢰"),
    CHAUSIE("쵸시"),
    PERSIAN_CHINCHILLA("페르시안 친칠라"),
    CHITO("치토"),
    COLORPOINT_SHORTHAIR("컬러포인트 쇼트헤어"),
    CORNISH_REX("코니시 렉스"),
    CYMRIC("킴릭"),
    DEVON_REX("데본 렉스"),
    DUTCH_REX("더치 렉스"),
    DONSKOY("돈스코이"),
    DRAGON_LI("드래곤 리"),
    ELF("엘프"),
    DWELF("드웰프"),
    EGYPTIAN_MAU("이집션 마우"),
    EUROPEAN_SHORTHAIR("유러피안 쇼트헤어"),
    EXOTIC_SHORTHAIR("이그저틱 쇼트헤어"),
    EXOTIC_LONGHAIR("이그저틱 롱헤어"),
    FOLDEX("폴덱스"),
    FOREIGN_WHITE("포린 화이트"),
    GENETTA("제네타"),
    GERMAN_REX("저먼 렉스"),
    HAVANA_BROWN("하바나 브라운"),
    HIGHLANDER("하일랜더"),
    HIMALAYAN("히말라얀"),
    JAG("재그"),
    JAPANESE_BOBTAIL("재패니즈 밥테일"),
    JAVANESE("자바니즈"),
    JUNGLE_BOB("정글밥"),
    KANANI("카나니"),
    KARELIAN_BOBTAIL("카렐리안 밥테일"),
    KASHMIR("카슈미르"),
    KHAO_MANEE("카오 마니"),
    KINKALOW("킨카로우"),
    KOHANA("코호나"),
    KORAT("코랏"),
    KORN_JA("콘 자"),
    KURILIAN_BOBTAIL("쿠릴리안 밥테일"),
    LAMBKIN("램킨"),
    LAPERM("라펌"),
    LYCYOI("라이코이"),
    MAINE_COON("메인쿤"),
    MALAYSIAN("말레이시아"),
    MANDALAY("만달레이"),
    MANX("맹크스"),
    MEKONG_BOBTAIL("메콩 밥테일"),
    MINSKIN("민스킨"),
    MINUET("미뉴에트"),
    MOJAVI_BOB("모하비밥"),
    MOJAVI_SPOTTED("모하비 점무늬"),
    MUNCHKIN("먼치킨"),
    NEBELUNG("네벨룽"),
    NEPALAYAN("네팔라얀"),
    NEVA_MASQUERADE("네바마스커레이드"),
    NEW_ZEALAND("뉴질랜드"),
    NORWEGIAN_FOREST("노르웨이 숲"),
    OCICAT("오시캣"),
    OJOS_AZULES("오호스 아즐레스"),
    OREGON_REX("오리건 렉스"),
    ORIENTAL_BICOLOR("오리엔탈 바이컬러"),
    ORIENTAL_LONGHAIR("오리엔탈 롱헤어"),
    ORIENTAL_SHORTHAIR("오리엔탈 쇼트헤어"),
    OWIHI_BOB("오위히 밥"),
    PERSIAN("페르시안"),
    TRADITIONAL_PERSIAN("트래디셔널 페르시안"),
    PANTHERETTE("팬서렛"),
    PETERBALD("피터볼드"),
    PIXIE_BOB("픽시 밥"),
    RAGAMUFFIN("라가머핀"),
    RAGDOLL("랙돌"),
    RAAS("라아스"),
    RUSSIAN_BLUE("러시안 블루"),
    RUSSIAN_WHITE("러시안 화이트"),
    RUSSIAN_BLACK("러시안 블랙"),
    RUSSIAN_TABBY("러시안 태비"),
    SAFARI("사파리"),
    SAM_SAWET("샘 사웨트"),
    SAVANNAH("사바나"),
    SCOTTISH_FOLD("스코티시 폴드"),
    SELKIRK_REX("셀커크 렉스"),
    SERENGETI("세렝게티"),
    SERRADE_PETITE("세라데 쁘띠"),
    SEYCHELLES("세이셸"),
    SIAMESE("샴"),
    SIBELLA("시벨라"),
    SIBERIAN("시베리안"),
    SINGAPURA("싱가푸라"),
    SKOOKUM("스쿠쿰"),
    SNOWSHOE("스노우슈"),
    SOKOKE("소코케"),
    SOMALI("소말리"),
    SPHYNX("스핑크스"),
    SUPHALAK("수팔락"),
    TENNESSEE_REX("테네시 렉스"),
    THAI("타이"),
    THAI_LILAC("타이 라일락"),
    THAI_BLUE_POINT("타이 블루 포인트"),
    THAI_LILAC_POINT("타이 라일락 포인트"),
    TIBETAN("티베탄"),
    TONKINESE("통키니즈"),
    TOYBOB("토이밥"),
    TOYGER("토이거"),
    TURKISH_ANGORA("터키시 앙고라"),
    TURKISH_VAN("터키시 반"),
    VAN("반"),
    UKRAINIAN_LEVKOY("유크레이니언 레브코이"),
    URAL_REX("우랄 렉스"),
    USSURI("우수리"),
    YORK_CHOCOLATE("요크 초콜릿");

    /***
     * 강아지 종류
     */

    private final String koreanName;

    Species(String koreanName) {
        this.koreanName = koreanName;
    }

    public String getKoreanName() {
        return koreanName;
    }
}

